version: '2'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: p@123
      MYSQL_DATABASE: sam
      MYSQL_USER: sam
      MYSQL_PASSWORD: p@123
  sam:
    image: sam
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      HTTP_PORT: 8080
      ADMIN_HTTP_PORT: 8081
      DB_CLASS_NAME: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: sam
      DB_USER: sam
      DB_PASSWORD: p@123
      
